### ISSUE TITLE
Naming of Solver

### ISSUE THREAD

**Issue by mykelk** [sisl/SARSOP.jl#3]
Should it be `SARSOPSolver` or just `Solver`? If you need to disambiguate, you can use `SARSOP.Solver`. Right?

**Comment by tawheeler** [comment]
This follows the convention of the other solvers.
QMDPSolver, POMCPSolver, ValueIterationSolver, MCTSSolver, etc.
Maybe post this on POMDPs.jl? You have a valid point, but it would be good to discuss with everything there.
